=== Narote-Dev/ThaiShopFun-OMS/contracts/schemas/rest/openid-configuration.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "issuer",
    "authorization_endpoint",
    "token_endpoint",
    "jwks_uri",
    "response_types_supported",
    "code_challenge_methods_supported",
    "grant_types_supported"
  ],
  "properties": {
    "issuer": {
      "type": "string",
      "minLength": 1
    },
    "authorization_endpoint": {
      "type": "string",
      "minLength": 1
    },
    "token_endpoint": {
      "type": "string",
      "minLength": 1
    },
    "jwks_uri": {
      "type": "string",
      "minLength": 1
    },
    "response_types_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subject_types_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "id_token_signing_alg_values_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "code_challenge_methods_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "grant_types_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "token_endpoint_auth_methods_supported": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== Narote-Dev/ThaiShopFun-OMS/contracts/examples/rest/openid-configuration.json
{
  "issuer": "http://localhost:8090/tsf-idp",
  "authorization_endpoint": "http://localhost:8090/tsf-idp/authorize",
  "token_endpoint": "http://localhost:8090/tsf-idp/token",
  "jwks_uri": "http://localhost:8090/tsf-idp/.well-known/jwks.json",
  "response_types_supported": [
    "code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "client_credentials"
  ],
  "token_endpoint_auth_methods_supported": [
    "none",
    "client_secret_post"
  ]
}
